### ISSUE TITLE
npm package not installable

### ISSUE THREAD

**Issue by mauritslamers** [falsecz/3-way-merge#2]
When installing the npm package, and then requiring causes an error, as the uploaded package on npmjs.org only contains the coffee script, but not the compiled version.

**Comment by markgithub3** [comment]
No need for compiled version, just register coffee script module beforehand like this:

```
require('coffee-script/register')

merge = require('3-way-merge')

console.log(merge({a: 1, b: 2}, {c: 3}, {b: 4}))
// outputs `{b: 4, c: 3}`
```

**Comment by mauritslamers** [comment]
Which assumes you have coffee-script installed and want to have it installed. The unsuspecting user does npm install, tries require and gets an error.

**Comment by mark33** [comment]
It's obviously module written in coffee script (with coffee script dependency in package.json). But I can see your point, we'll maybe rewrite it to pure JS later

**Comment by markgithub3** [comment]
Fixed in the latest version. Sorry for the misunderstanding and thanks for your input, Maurits! And @falsecz for explaining it to me :)
